# Generated by Django 5.0.7 on 2024-07-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login',
            new_name='last_active',
        ),
    ]
