# Generated by Django 5.0.7 on 2024-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_last_login_user_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='private/'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='public/'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(upload_to='public/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='public/'),
        ),
    ]
